#!/usr/bin/env bash
# Fixes a web server tp run Nginx as tje nginx user listening on port 8000.
sed -i "s/#user www-data/user nginx/" etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/ginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
